In [102]:
import pandas as pd

In [103]:
from sqlalchemy import create_engine

In [104]:
df = pd.read_csv('ks-projects-201612.csv', encoding = 'latin-1')

/var/folders/bd/dktt89416b95w0mckdnfqm0w0000gn/T/ipykernel_5529/3917055923.py:1: DtypeWarning: Columns (0: Unnamed: 13, 1: Unnamed: 14, 2: Unnamed: 15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('ks-projects-201612.csv', encoding = 'latin-1')

In [105]:
df

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09 11:36:00,1000,2015-08-11 12:12:28,0,failed,0,GB,0,NaN,NaN,NaN,NaN
1,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26 00:20:50,45000,2013-01-12 00:20:50,220,failed,3,US,220,NaN,NaN,NaN,NaN
2,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16 04:24:11,5000,2012-03-17 03:24:11,1,failed,1,US,1,NaN,NaN,NaN,NaN
3,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29 01:00:00,19500,2015-07-04 08:35:03,1283,canceled,14,US,1283,NaN,NaN,NaN,NaN
4,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01 13:38:27,50000,2016-02-26 13:38:27,52375,successful,224,US,52375,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323745,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17 02:35:30,50000,2014-09-17 02:35:30,25,canceled,1,US,25,NaN,NaN,NaN,NaN
323746,999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19 03:35:14,1500,2011-06-22 03:35:14,155,failed,5,US,155,NaN,NaN,NaN,NaN
323747,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16 05:59:00,15000,2010-07-01 19:40:30,20,failed,1,US,20,NaN,NaN,NaN,NaN
323748,999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13 02:00:00,15000,2016-01-13 18:13:53,200,failed,6,US,200,NaN,NaN,NaN,NaN
323749,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16 09:07:47,2000,2011-07-19 09:07:47,524,failed,17,US,524,NaN,NaN,NaN,NaN

In [106]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 323750 entries, 0 to 323749
Data columns (total 17 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID              323750 non-null  int64
 1   name            323746 non-null  str
 2   category        323745 non-null  str
 3   main_category   323750 non-null  str
 4   currency        323750 non-null  str
 5   deadline        323750 non-null  str
 6   goal            323750 non-null  str
 7   launched        323750 non-null  str
 8   pledged         323750 non-null  str
 9   state           323750 non-null  str
 10  backers         323750 non-null  str
 11  country         323750 non-null  str
 12  usd pledged     319960 non-null  str
 13  Unnamed: 13     625 non-null     object
 14  Unnamed: 14     12 non-null      object
 15  Unnamed: 15     4 non-null       object
 16  Unnamed: 16     1 non-null       float64
dtypes: float64(1), int64(1), object(3), str(12)
memory usage: 42.0+ MB

In [107]:
df.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09 11:36:00,1000,2015-08-11 12:12:28,0,failed,0,GB,0,NaN,NaN,NaN,NaN
1,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26 00:20:50,45000,2013-01-12 00:20:50,220,failed,3,US,220,NaN,NaN,NaN,NaN
2,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16 04:24:11,5000,2012-03-17 03:24:11,1,failed,1,US,1,NaN,NaN,NaN,NaN
3,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29 01:00:00,19500,2015-07-04 08:35:03,1283,canceled,14,US,1283,NaN,NaN,NaN,NaN
4,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01 13:38:27,50000,2016-02-26 13:38:27,52375,successful,224,US,52375,NaN,NaN,NaN,NaN

In [108]:
df.columns

Index(['ID ', 'name ', 'category ', 'main_category ', 'currency ', 'deadline ',
       'goal ', 'launched ', 'pledged ', 'state ', 'backers ', 'country ',
       'usd pledged ', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16'],
      dtype='str')

In [109]:
df.shape

(323750, 17)

In [110]:
df.dtypes

ID                  int64
name                  str
category              str
main_category         str
currency              str
deadline              str
goal                  str
launched              str
pledged               str
state                 str
backers               str
country               str
usd pledged           str
Unnamed: 13        object
Unnamed: 14        object
Unnamed: 15        object
Unnamed: 16       float64
dtype: object

In [111]:
df.isnull().sum()

ID                     0
name                   4
category               5
main_category          0
currency               0
deadline               0
goal                   0
launched               0
pledged                0
state                  0
backers                0
country                0
usd pledged         3790
Unnamed: 13       323125
Unnamed: 14       323738
Unnamed: 15       323746
Unnamed: 16       323749
dtype: int64

In [112]:
df.drop(columns = ['Unnamed: 13','Unnamed: 16'], inplace = True)

In [113]:
df.drop(columns = ['Unnamed: 14', 'Unnamed: 15'], inplace = True)

In [114]:
print(repr(df.columns[0]))

'ID '

In [115]:
df.columns = df.columns.str.strip().str.replace(' ', '_').str.strip('_')

In [116]:
df[df['name'].isnull()]

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
142830,1848699072,NaN,Narrative Film,Film & Video,USD,2012-02-29 15:04:00,200000,2012-01-01 12:35:31,100,failed,1,US,100
262901,634871725,NaN,Video Games,Games,GBP,2013-01-06 23:00:00,2000,2012-12-19 23:57:48,196,failed,12,GB,317.7284362
265251,648853978,NaN,Product Design,Design,USD,2016-07-18 05:01:47,2500,2016-06-18 05:01:47,0,suspended,0,US,0
289847,796533179,NaN,Painting,Art,USD,2011-12-05 05:59:00,35000,2011-11-06 23:55:55,220,failed,5,US,220

In [117]:
df['name'].unique()

<StringArray>
[                                        'The Songs of Adelaide & Abullah',
                                                          'Where is Hank?',
                       'ToshiCapital Rekordz Needs Help to Complete Album',
              'Community Film Project: The Art of Neighborhood Filmmaking',
                                                    'Monarch Espresso Bar',
            'Support Solar Roasted Coffee & Green Energy!  SolarCoffee.co',
                       'Chaser Strips. Our Strips make Shots their B*tch!',
                   'SPIN - Premium Retractable In-Ear Headphones with Mic',
               'STUDIO IN THE SKY - A Documentary Feature Film (Canceled)',
                                                     'Of Jesus and Madmen',
 ...
                                              'Date Seat - Boston iOS App',
                                                            'AT THE BEACH',
                                             'Beach Wrestling Documentary',
                                                                 'Islanda',
                                              'Angela's Poetry (Canceled)',
                       'ChknTruk Nationwide Charity Drive 2014 (Canceled)',
                                                               'The Tribe',
 'Walls of Remedy- New lesbian Romantic Comedy feature unlike any other!!',
                                                'BioDefense Education Kit',
                                       'Nou Renmen Ayiti!  We Love Haiti!']
Length: 321613, dtype: str

In [118]:
df['name'] = df['name'].fillna('Unknown')

In [119]:
df['name'].isnull().sum()

np.int64(0)

In [120]:
df[df['category'].isnull()]

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
36671,1218074363,I am Rupert,NaN,Webseries,Film & Video,GBP,2014-05-16 22:25:57,2000,2014-03-27 21:25:57,5,failed,1,GB
41069,124438738,BlanketPals TM,NaN,Interactive Design,Design,USD,2015-03-25 20:51:48,9750,2015-02-23 21:51:48,10890.45,successful,107,US
63544,1378236004,{string&&loop} Knitting Craft with Code,NaN,Apparel,Fashion,USD,2016-05-28 00:00:00,1800,2016-04-29 21:04:40,2308,successful,119,US
96753,1574873938,American Pin-up Revisitedd,NaN,Art,Art,USD,2014-04-03 17:52:09,7500,2014-03-04 17:52:09,100,failed,1,US
269930,676846639,Uplift: The Wearable iPhone Case with Zipline&...,NaN,Design,Design,USD,2011-04-04 20:08:17,50000,2011-03-05 20:08:17,1665,canceled,10,US

In [121]:
df['category'].unique()

<StringArray>
[                            'Poetry',                     'Narrative Film',
                              'Music',                       'Film & Video',
                        'Restaurants',                               'Food',
                             'Drinks',                     'Product Design',
                        'Documentary',                         'Nonfiction',
 ...
             'float:left} (Canceled)',                 ' The Trip for Life',
                  ' defying the odds', ' The store you've been looking for',
                      ' Major Arcana',  ' MY LIFE IN THE MISSISSIPPI DELTA',
                  ' so get on board!',                ' Head in the Clouds',
                   ' Post Production',       ' a bike quest in New Zealand']
Length: 771, dtype: str

In [122]:
df[df['main_category'] == 'Apparel']

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
28830,1170757079,Luxe Neckwear,Next Generation Ties,Apparel,Fashion,USD,2015-03-27 21:49:10,75000,2015-02-25 22:49:10,166,failed,2,US
63544,1378236004,{string&&loop} Knitting Craft with Code,NaN,Apparel,Fashion,USD,2016-05-28 00:00:00,1800,2016-04-29 21:04:40,2308,successful,119,US
66484,1395178749,Warrior Wear - Men's Yoga Shorts,Optimized for Performance.,Apparel,Fashion,USD,2016-06-23 16:31:58,5000,2016-05-24 16:31:58,6453,successful,77,US
82927,1492555128,Tranzishyn Never Settle,not just a brand but a philosophy.,Apparel,Fashion,USD,2015-03-21 23:58:38,6000,2015-02-20 00:58:38,115,failed,4,US
98265,1583652438,**ALL NEW** Purpose Driven Activewear,Fashion with Purpose,Apparel,Fashion,USD,2016-04-19 00:19:18,3500,2016-03-14 23:19:18,191,failed,6,US
148002,1879249811,Femme-Fatale Lingerie,sophisticated vintage inspiration!,Apparel,Fashion,GBP,2016-12-20 20:00:00,5000,2016-11-22 10:35:21,10564,live,91,GB
193157,217204038,OsoPorto T-shirts & Prints | modern design,SoCal style,Apparel,Fashion,USD,2014-07-25 04:11:00,5500,2014-06-26 00:51:04,6972.6,successful,124,US
243901,519956154,Anyone Can Be An Astronaut,Summer Collection,Apparel,Fashion,USD,2014-06-13 19:46:46,3000,2014-06-06 19:46:46,0,failed,0,US
280626,740875655,The Warr,or Project,Apparel,Fashion,GBP,2015-08-22 13:04:58,350,2015-08-08 13:04:58,52,failed,1,GB
312084,929880656,Nekter Apparel,Help us revolutionize the hoodie industry,Apparel,Fashion,USD,2016-02-20 21:08:22,10000,2016-01-21 21:08:22,0,failed,0,US

In [123]:
df.loc[36671, 'category'] = 'Webseries'
df.loc[41069, 'category'] = 'Interactive Design'
df.loc[63544, 'category'] = 'Unknown'
df.loc[96753, 'category'] = 'Art'
df.loc[269930, 'category'] = 'Design'

In [124]:
df['category'].isnull().sum()

np.int64(0)

In [125]:
df[df['usd_pledged'].isnull()]

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
150,1000694855,STREETFIGHTERZ WHEELIE MURICA,Film & Video,Film & Video,USD,2014-09-20 06:59:00,6500,2014-08-06 21:28:36,555,undefined,0,"N,""0",NaN
287,100149523,Duncan Woods - Chameleon EP,Music,Music,AUD,2015-08-25 23:00:00,4500,2015-08-04 12:05:17,4767,undefined,0,"N,""0",NaN
549,1003023003,The Making of Ashley Kelley's Debut Album,Music,Music,USD,2015-04-09 21:06:13,3500,2015-03-10 20:06:13,3576,undefined,0,"N,""0",NaN
561,1003130892,Butter Side Down Debut Album,Music,Music,USD,2015-11-26 10:59:00,6000,2015-11-02 22:09:19,7007.8,undefined,0,"N,""0",NaN
650,1003629045,Chase Goehring debut EP,Music,Music,USD,2016-03-21 06:00:00,3000,2016-02-23 03:09:49,3660.38,undefined,0,"N,""0",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
323391,997971307,"EQUUS International Film Festival®, all-equine...",Film & Video,Film & Video,USD,2015-02-03 04:19:14,7500,2014-12-05 04:19:14,10,undefined,0,"N,""0",NaN
323456,998319149,Emily 2050 - Short Film,Film & Video,Film & Video,CAD,2014-05-23 00:30:09,3000,2014-04-08 00:30:09,3102,undefined,0,"N,""0",NaN
323561,9988744,Matthew Stephens Music,Music,Music,USD,2016-02-05 23:00:00,5000,2016-01-06 21:59:23,235,undefined,0,"N,""0",NaN
323683,999610349,Lady Vendredi: Afrofuturist concept 12 inch EP,Music,Music,GBP,2015-10-19 22:33:18,2000,2015-09-21 22:33:18,2125,undefined,0,"N,""0",NaN
323685,999621278,Jeune auteur a besoin de vous!,Publishing,Publishing,EUR,2015-11-20 21:28:13,1600,2015-10-21 21:28:13,0,undefined,0,"N,""0",NaN

In [126]:
df['usd_pledged'].unique()

<StringArray>
[            '0',           '220',             '1',          '1283',
         '52375',          '1205',           '453',          '8233',
       '6240.57',         '12700',
 ...
          '8935',         '42647',  '1673.7131361', '1937.69716526',
       '13861.5',  '4814.8774787',  '4281.1485734',       '1732.02',
 '5019.92088197',   '2698.974335']
Length: 94377, dtype: str

In [127]:
df[df['usd_pledged'] == '0']

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09 11:36:00,1000,2015-08-11 12:12:28,0,failed,0,GB,0
9,100004721,Of Jesus and Madmen,Nonfiction,Publishing,CAD,2013-10-09 18:19:37,2500,2013-09-09 18:19:37,0,failed,0,CA,0
11,1000055792,The Cottage Market,Crafts,Crafts,USD,2014-10-02 17:11:50,5000,2014-09-02 17:11:50,0,failed,0,US,0
12,1000056157,G-Spot Place for Gamers to connect with eachot...,Games,Games,USD,2016-03-25 22:01:12,200000,2016-02-09 23:01:12,0,failed,0,US,0
23,1000103948,Superhero Teddy Bear,DIY,Crafts,GBP,2016-01-05 20:09:06,12000,2015-12-06 20:09:06,0,failed,0,GB,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
323725,99984851,"""Loreto""",Comedy,Film & Video,USD,2014-06-05 06:00:00,12000,2014-05-06 23:50:34,0,failed,0,US,0
323733,99991751,Here is the oasis for the youngest in the world.,Product Design,Design,CHF,2015-09-04 18:00:47,80000,2015-07-06 18:00:47,0,failed,0,CH,0
323734,999931480,Google Glass Shield (Canceled),3D Printing,Technology,USD,2014-05-26 20:22:45,6500,2014-05-05 20:22:45,0,canceled,0,US,0
323740,99996661,Date Seat - Boston iOS App,Apps,Technology,USD,2016-09-05 05:59:00,6000,2016-07-29 15:36:29,0,failed,0,US,0
323744,999976312,Angela's Poetry (Canceled),Poetry,Publishing,CAD,2014-09-20 03:46:07,5500,2014-08-06 03:46:07,0,canceled,0,CA,0

In [128]:
df['pledged'].unique()

<StringArray>
[      '0',     '220',       '1',    '1283',   '52375',    '1205',     '453',
    '8233', '6240.57',   '12700',
 ...
   '65200', '58355.5', '4307.05',   '28931',   '14646',    '8462',    '8935',
   '42647', '13861.5', '1732.02']
Length: 55598, dtype: str

In [129]:
df[df['pledged'] == '3102']

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
3140,1018824318,SUMMER AND SMOKE - Debut EP from The Lost Wayne,Music,Music,USD,2014-12-06 18:24:12,2000,2014-11-06 18:24:12,3102,undefined,0,"N,""0",NaN
40589,1241491142,Pre-order Dan Gurney's debut solo album,Music,Music,USD,2011-04-12 07:35:17,3000,2011-03-12 07:35:17,3102,successful,60,US,3102
70153,1416715947,Natalie Ryan's Sophomore EP,Indie Rock,Music,USD,2014-04-05 18:55:01,3000,2014-03-04 18:55:01,3102,successful,52,US,3102
88837,152810052,Band - IT ALL SuperStrong RubberBands - 4 Grip...,Product Design,Design,USD,2015-01-04 07:15:18,5000,2014-11-25 07:15:18,3102,failed,22,US,3102
100329,1596028993,Pursuing Life: Headed West,Places,Photography,USD,2014-07-12 07:59:00,3000,2014-06-19 22:55:49,3102,successful,44,US,3102
101321,1602115671,FTR: For The Realm - Chapter 01,Comic Books,Comics,USD,2015-04-25 00:00:00,3000,2015-04-01 18:18:25,3102,successful,39,US,3102
108750,1645650903,The SunFlower Project,Public Art,Art,USD,2012-03-21 00:30:00,3000,2012-02-18 21:10:45,3102,successful,22,US,3102
109677,1650943044,Skinny-E (EP),Music,Music,USD,2016-08-23 17:20:35,20000,2016-08-02 17:20:35,3102,failed,58,US,270
131952,1783416366,Relics Issue #0,Comic Books,Comics,USD,2016-09-01 01:52:35,1500,2016-08-02 01:52:35,3102,successful,88,US,739
141877,1843341212,The Jezebelles Debut EP Coming Soon!,Rock,Music,USD,2013-03-03 05:21:39,3000,2013-02-01 05:21:39,3102,successful,33,US,3102
173792,2034372709,The Compost Chopper,Product Design,Design,USD,2014-07-14 05:00:00,12000,2014-06-03 16:59:48,3102,failed,61,US,3102
223392,397598356,Percy Jones Scott McGill Ritchie DeCarlo,Music,Music,USD,2014-08-16 01:00:00,2800,2014-07-21 19:47:33,3102,undefined,0,"N,""0",NaN
240035,497046469,LUX CABLES | The Premium Charging Cable | USB ...,Technology,Technology,CAD,2016-08-15 01:53:43,5000,2016-06-16 01:53:43,3102,canceled,37,CA,2419.93050288
284938,766965683,We've Cracked the Code - All Kids Can Learn to...,Apps,Technology,USD,2014-07-18 04:57:00,10000,2014-06-12 09:03:21,3102,failed,53,US,3102
301635,867114835,Homestead Honey Farm : bee yard expansion and ...,Food,Food,USD,2013-03-25 00:04:59,1800,2013-02-23 01:04:59,3102,successful,83,US,3102
306432,895888340,Texas Tears - Habanero Sauce,Food,Food,USD,2013-10-26 03:00:00,5775,2013-09-10 17:51:44,3102,failed,96,US,3102
307636,903175777,Moving Forward And Coming Home,Mixed Media,Art,USD,2012-05-31 01:02:54,3000,2012-05-01 01:02:54,3102,successful,67,US,3102
323456,998319149,Emily 2050 - Short Film,Film & Video,Film & Video,CAD,2014-05-23 00:30:09,3000,2014-04-08 00:30:09,3102,undefined,0,"N,""0",NaN

In [130]:
df[df['usd_pledged'].isnull()]['currency'].value_counts()

currency
USD    2733
GBP     459
CAD     205
EUR     186
AUD     111
SEK      31
NZD      28
DKK      16
NOK      14
CHF       7
Name: count, dtype: int64

In [131]:
usd_mask = (df['usd_pledged'].isnull()) & (df['currency'] == 'USD')
df.loc[usd_mask, 'usd_pledged'] = df.loc[usd_mask, 'pledged']

In [132]:
df[df['usd_pledged'].isnull()]

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
287,100149523,Duncan Woods - Chameleon EP,Music,Music,AUD,2015-08-25 23:00:00,4500,2015-08-04 12:05:17,4767,undefined,0,"N,""0",NaN
714,1004013077,Spencer Capier Instrumental Project 2015,Music,Music,CAD,2014-10-10 22:51:01,4000,2014-09-10 22:51:01,4760,undefined,0,"N,""0",NaN
891,100522240,DO NOT DUPLICATE - Selected by 2015 Devon Film...,Film & Video,Film & Video,GBP,2015-04-10 23:07:00,1500,2015-03-11 22:07:00,277,undefined,0,"N,""0",NaN
1447,1008671527,The Fitness Mindset :-),Publishing,Publishing,EUR,2015-11-17 15:45:38,8000,2015-10-13 15:45:38,30,undefined,0,"N,""0",NaN
1685,1010217550,Solarboot-Havel-Tour,Music,Music,EUR,2015-05-31 22:37:00,2500,2015-05-14 23:05:51,2620,undefined,0,"N,""0",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
323077,99613274,Double EP and Music Video Fundraiser,Music,Music,GBP,2015-12-02 21:00:00,3000,2015-11-02 09:33:38,3517,undefined,0,"N,""0",NaN
323275,99739483,No More Fear,Music,Music,GBP,2016-04-17 01:00:00,2500,2016-03-17 13:43:26,2500,undefined,0,"N,""0",NaN
323456,998319149,Emily 2050 - Short Film,Film & Video,Film & Video,CAD,2014-05-23 00:30:09,3000,2014-04-08 00:30:09,3102,undefined,0,"N,""0",NaN
323683,999610349,Lady Vendredi: Afrofuturist concept 12 inch EP,Music,Music,GBP,2015-10-19 22:33:18,2000,2015-09-21 22:33:18,2125,undefined,0,"N,""0",NaN
323685,999621278,Jeune auteur a besoin de vous!,Publishing,Publishing,EUR,2015-11-20 21:28:13,1600,2015-10-21 21:28:13,0,undefined,0,"N,""0",NaN

In [133]:
df[(df['usd_pledged'].isnull()) & (df['pledged'] == '0')]

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
3111,1018672158,Struggle,Film & Video,Film & Video,CAD,2015-12-02 20:51:57,4100,2015-11-02 20:51:57,0,undefined,0,"N,""0",NaN
5162,1030879617,YAY! Your Amazing Year: YOU CAN! Life Coach Yo...,Publishing,Publishing,GBP,2015-12-15 20:12:04,4650,2015-11-15 20:12:04,0,undefined,0,"N,""0",NaN
6593,1038761532,the studio,Film & Video,Film & Video,GBP,2015-03-31 19:56:00,3000,2015-02-17 23:50:31,0,undefined,0,"N,""0",NaN
7230,1042565336,Ticket Buddy,Music,Music,GBP,2016-04-05 17:13:26,1000,2016-03-06 17:13:26,0,undefined,0,"N,""0",NaN
8658,1050790557,"Leicester's Days of Glory, a 360º Virtual Real...",Film & Video,Film & Video,GBP,2016-05-29 20:55:34,6000,2016-05-15 20:55:34,0,failed,0,"N,""0",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
319387,973573632,Endless - New Age Piano Album,Music,Music,EUR,2015-07-18 12:50:41,5000,2015-06-18 12:50:41,0,undefined,0,"N,""0",NaN
319530,974465386,Support Twotubers,Film & Video,Film & Video,EUR,2016-04-11 23:32:45,2000,2016-02-11 23:32:45,0,undefined,0,"N,""0",NaN
320925,982862687,Bydlo - A Novel,Publishing,Publishing,GBP,2015-06-01 12:51:16,3000,2015-04-02 12:51:16,0,undefined,0,"N,""0",NaN
322881,994911312,"""Songwriter assistance"" service",Music,Music,CAD,2014-12-22 00:56:04,5000,2014-11-22 00:56:04,0,undefined,0,"N,""0",NaN
323685,999621278,Jeune auteur a besoin de vous!,Publishing,Publishing,EUR,2015-11-20 21:28:13,1600,2015-10-21 21:28:13,0,undefined,0,"N,""0",NaN

In [134]:
zero_mask = (df['usd_pledged'].isnull()) & (df['pledged'] == '0')
df.loc[zero_mask, 'usd_pledged'] = '0'

In [135]:
df['usd_pledged'].isnull().sum()

np.int64(845)

In [136]:
df[df['usd_pledged'].isnull()]['currency'].value_counts()

currency
GBP    381
CAD    166
EUR    132
AUD     89
SEK     27
NZD     23
DKK     11
NOK     10
CHF      6
Name: count, dtype: int64

In [137]:
df[df['usd_pledged'].isnull()]

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
287,100149523,Duncan Woods - Chameleon EP,Music,Music,AUD,2015-08-25 23:00:00,4500,2015-08-04 12:05:17,4767,undefined,0,"N,""0",NaN
714,1004013077,Spencer Capier Instrumental Project 2015,Music,Music,CAD,2014-10-10 22:51:01,4000,2014-09-10 22:51:01,4760,undefined,0,"N,""0",NaN
891,100522240,DO NOT DUPLICATE - Selected by 2015 Devon Film...,Film & Video,Film & Video,GBP,2015-04-10 23:07:00,1500,2015-03-11 22:07:00,277,undefined,0,"N,""0",NaN
1447,1008671527,The Fitness Mindset :-),Publishing,Publishing,EUR,2015-11-17 15:45:38,8000,2015-10-13 15:45:38,30,undefined,0,"N,""0",NaN
1685,1010217550,Solarboot-Havel-Tour,Music,Music,EUR,2015-05-31 22:37:00,2500,2015-05-14 23:05:51,2620,undefined,0,"N,""0",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
321973,989218116,Keep on Movin' - The Debut Album,Music,Music,GBP,2014-11-19 22:22:14,1300,2014-10-22 22:22:14,2,undefined,0,"N,""0",NaN
323077,99613274,Double EP and Music Video Fundraiser,Music,Music,GBP,2015-12-02 21:00:00,3000,2015-11-02 09:33:38,3517,undefined,0,"N,""0",NaN
323275,99739483,No More Fear,Music,Music,GBP,2016-04-17 01:00:00,2500,2016-03-17 13:43:26,2500,undefined,0,"N,""0",NaN
323456,998319149,Emily 2050 - Short Film,Film & Video,Film & Video,CAD,2014-05-23 00:30:09,3000,2014-04-08 00:30:09,3102,undefined,0,"N,""0",NaN
323683,999610349,Lady Vendredi: Afrofuturist concept 12 inch EP,Music,Music,GBP,2015-10-19 22:33:18,2000,2015-09-21 22:33:18,2125,undefined,0,"N,""0",NaN

In [138]:
845 / len(df) * 100

0.261003861003861

In [139]:
df = df.dropna(subset = ['usd_pledged'])

In [140]:
df['usd_pledged'].isnull().sum()

np.int64(0)

In [ ]:
df.to_sql(
  name = 'ks_projects',
  con = engine,
  if_exists = 'append',
  index = False
)
print('Successfully added and loaded to kickstarter db')

In [ ]:
sql_query = """
SELECT *
FROM ks_projects
LIMIT 20; """

In [ ]:
df_all = pd.read_sql(sql_query, con=engine)
df_all