In [18]:
import pandas as pd

In [19]:
from sqlalchemy import create_engine

In [20]:
df = pd.read_csv('ks-projects-201612.csv', encoding = 'latin-1')

/var/folders/bd/dktt89416b95w0mckdnfqm0w0000gn/T/ipykernel_5529/3917055923.py:1: DtypeWarning: Columns (0: Unnamed: 13, 1: Unnamed: 14, 2: Unnamed: 15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('ks-projects-201612.csv', encoding = 'latin-1')

In [21]:
df

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09 11:36:00,1000,2015-08-11 12:12:28,0,failed,0,GB,0,NaN,NaN,NaN,NaN
1,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26 00:20:50,45000,2013-01-12 00:20:50,220,failed,3,US,220,NaN,NaN,NaN,NaN
2,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16 04:24:11,5000,2012-03-17 03:24:11,1,failed,1,US,1,NaN,NaN,NaN,NaN
3,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29 01:00:00,19500,2015-07-04 08:35:03,1283,canceled,14,US,1283,NaN,NaN,NaN,NaN
4,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01 13:38:27,50000,2016-02-26 13:38:27,52375,successful,224,US,52375,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323745,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17 02:35:30,50000,2014-09-17 02:35:30,25,canceled,1,US,25,NaN,NaN,NaN,NaN
323746,999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19 03:35:14,1500,2011-06-22 03:35:14,155,failed,5,US,155,NaN,NaN,NaN,NaN
323747,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16 05:59:00,15000,2010-07-01 19:40:30,20,failed,1,US,20,NaN,NaN,NaN,NaN
323748,999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13 02:00:00,15000,2016-01-13 18:13:53,200,failed,6,US,200,NaN,NaN,NaN,NaN
323749,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16 09:07:47,2000,2011-07-19 09:07:47,524,failed,17,US,524,NaN,NaN,NaN,NaN

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 323750 entries, 0 to 323749
Data columns (total 17 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID              323750 non-null  int64
 1   name            323746 non-null  str
 2   category        323745 non-null  str
 3   main_category   323750 non-null  str
 4   currency        323750 non-null  str
 5   deadline        323750 non-null  str
 6   goal            323750 non-null  str
 7   launched        323750 non-null  str
 8   pledged         323750 non-null  str
 9   state           323750 non-null  str
 10  backers         323750 non-null  str
 11  country         323750 non-null  str
 12  usd pledged     319960 non-null  str
 13  Unnamed: 13     625 non-null     object
 14  Unnamed: 14     12 non-null      object
 15  Unnamed: 15     4 non-null       object
 16  Unnamed: 16     1 non-null       float64
dtypes: float64(1), int64(1), object(3), str(12)
memory usage: 42.0+ MB

In [23]:
df.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09 11:36:00,1000,2015-08-11 12:12:28,0,failed,0,GB,0,NaN,NaN,NaN,NaN
1,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26 00:20:50,45000,2013-01-12 00:20:50,220,failed,3,US,220,NaN,NaN,NaN,NaN
2,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16 04:24:11,5000,2012-03-17 03:24:11,1,failed,1,US,1,NaN,NaN,NaN,NaN
3,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29 01:00:00,19500,2015-07-04 08:35:03,1283,canceled,14,US,1283,NaN,NaN,NaN,NaN
4,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01 13:38:27,50000,2016-02-26 13:38:27,52375,successful,224,US,52375,NaN,NaN,NaN,NaN

In [24]:
df.columns

Index(['ID ', 'name ', 'category ', 'main_category ', 'currency ', 'deadline ',
       'goal ', 'launched ', 'pledged ', 'state ', 'backers ', 'country ',
       'usd pledged ', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16'],
      dtype='str')

In [25]:
df.shape

(323750, 17)

In [26]:
df.dtypes

ID                  int64
name                  str
category              str
main_category         str
currency              str
deadline              str
goal                  str
launched              str
pledged               str
state                 str
backers               str
country               str
usd pledged           str
Unnamed: 13        object
Unnamed: 14        object
Unnamed: 15        object
Unnamed: 16       float64
dtype: object

In [27]:
print(repr(df.columns[0]))

'ID '

In [28]:
df.isnull().sum()

ID                     0
name                   4
category               5
main_category          0
currency               0
deadline               0
goal                   0
launched               0
pledged                0
state                  0
backers                0
country                0
usd pledged         3790
Unnamed: 13       323125
Unnamed: 14       323738
Unnamed: 15       323746
Unnamed: 16       323749
dtype: int64

In [29]:
df.drop(columns = ['Unnamed: 13','Unnamed: 16'], inplace = True)

In [30]:
df.drop(columns = ['Unnamed: 14', 'Unnamed: 15'], inplace = True)

In [31]:
df.columns = df.columns.str.strip().str.replace(' ', '_').str.strip('_')

In [38]:
df[df['name'].isnull()]

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
142830,1848699072,NaN,Narrative Film,Film & Video,USD,2012-02-29 15:04:00,200000,2012-01-01 12:35:31,100,failed,1,US,100
262901,634871725,NaN,Video Games,Games,GBP,2013-01-06 23:00:00,2000,2012-12-19 23:57:48,196,failed,12,GB,317.7284362
265251,648853978,NaN,Product Design,Design,USD,2016-07-18 05:01:47,2500,2016-06-18 05:01:47,0,suspended,0,US,0
289847,796533179,NaN,Painting,Art,USD,2011-12-05 05:59:00,35000,2011-11-06 23:55:55,220,failed,5,US,220

In [43]:
df['name'].unique()

<StringArray>
[                                        'The Songs of Adelaide & Abullah',
                                                          'Where is Hank?',
                       'ToshiCapital Rekordz Needs Help to Complete Album',
              'Community Film Project: The Art of Neighborhood Filmmaking',
                                                    'Monarch Espresso Bar',
            'Support Solar Roasted Coffee & Green Energy!  SolarCoffee.co',
                       'Chaser Strips. Our Strips make Shots their B*tch!',
                   'SPIN - Premium Retractable In-Ear Headphones with Mic',
               'STUDIO IN THE SKY - A Documentary Feature Film (Canceled)',
                                                     'Of Jesus and Madmen',
 ...
                                              'Date Seat - Boston iOS App',
                                                            'AT THE BEACH',
                                             'Beach Wrestling Documentary',
                                                                 'Islanda',
                                              'Angela's Poetry (Canceled)',
                       'ChknTruk Nationwide Charity Drive 2014 (Canceled)',
                                                               'The Tribe',
 'Walls of Remedy- New lesbian Romantic Comedy feature unlike any other!!',
                                                'BioDefense Education Kit',
                                       'Nou Renmen Ayiti!  We Love Haiti!']
Length: 321613, dtype: str

In [39]:
df[df['category'].isnull()]

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
36671,1218074363,I am Rupert,NaN,Webseries,Film & Video,GBP,2014-05-16 22:25:57,2000,2014-03-27 21:25:57,5,failed,1,GB
41069,124438738,BlanketPals TM,NaN,Interactive Design,Design,USD,2015-03-25 20:51:48,9750,2015-02-23 21:51:48,10890.45,successful,107,US
63544,1378236004,{string&&loop} Knitting Craft with Code,NaN,Apparel,Fashion,USD,2016-05-28 00:00:00,1800,2016-04-29 21:04:40,2308,successful,119,US
96753,1574873938,American Pin-up Revisitedd,NaN,Art,Art,USD,2014-04-03 17:52:09,7500,2014-03-04 17:52:09,100,failed,1,US
269930,676846639,Uplift: The Wearable iPhone Case with Zipline&...,NaN,Design,Design,USD,2011-04-04 20:08:17,50000,2011-03-05 20:08:17,1665,canceled,10,US

In [44]:
df['category'].unique()

<StringArray>
[                            'Poetry',                     'Narrative Film',
                              'Music',                       'Film & Video',
                        'Restaurants',                               'Food',
                             'Drinks',                     'Product Design',
                        'Documentary',                         'Nonfiction',
 ...
             'float:left} (Canceled)',                 ' The Trip for Life',
                  ' defying the odds', ' The store you've been looking for',
                      ' Major Arcana',  ' MY LIFE IN THE MISSISSIPPI DELTA',
                  ' so get on board!',                ' Head in the Clouds',
                   ' Post Production',       ' a bike quest in New Zealand']
Length: 771, dtype: str

In [46]:
df[df['main_category'] == 'Webseries']

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
36671,1218074363,I am Rupert,NaN,Webseries,Film & Video,GBP,2014-05-16 22:25:57,2000,2014-03-27 21:25:57,5,failed,1,GB
65062,1387078972,Dateless The Series,Come be a part of the fun!,Webseries,Film & Video,USD,2013-12-15 16:54:00,9200,2013-11-15 16:54:00,9857.8,successful,150,US
152406,1905775245,Music Today,The Making Of,Webseries,Film & Video,GBP,2016-11-27 21:02:43,110,2016-10-28 21:02:43,110,successful,12,GB
168639,2003625595,Classic Automobile,designs innovations and inspirations.,Webseries,Film & Video,USD,2011-04-29 19:04:32,50000,2011-03-30 19:04:32,25,failed,1,US
200622,261815937,Pop Culture Purposed (a web show,title tbd) (Canceled),Webseries,Film & Video,USD,2014-03-23 15:50:11,96100,2014-01-22 16:50:11,170,canceled,3,US
230636,441511653,Couch2Kitchen Kids Edition,Off The Couch & Into The Kitchen,Webseries,Film & Video,USD,2015-06-30 07:00:00,10130,2015-05-16 14:41:53,1665,failed,19,US
282496,752380461,Depressed Girl,Changing the Way People See Mental Illness,Webseries,Film & Video,USD,2014-12-11 08:53:26,500,2014-11-11 08:53:26,145,failed,3,US

In [42]:
df[df['usd_pledged'].isnull()]

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
150,1000694855,STREETFIGHTERZ WHEELIE MURICA,Film & Video,Film & Video,USD,2014-09-20 06:59:00,6500,2014-08-06 21:28:36,555,undefined,0,"N,""0",NaN
287,100149523,Duncan Woods - Chameleon EP,Music,Music,AUD,2015-08-25 23:00:00,4500,2015-08-04 12:05:17,4767,undefined,0,"N,""0",NaN
549,1003023003,The Making of Ashley Kelley's Debut Album,Music,Music,USD,2015-04-09 21:06:13,3500,2015-03-10 20:06:13,3576,undefined,0,"N,""0",NaN
561,1003130892,Butter Side Down Debut Album,Music,Music,USD,2015-11-26 10:59:00,6000,2015-11-02 22:09:19,7007.8,undefined,0,"N,""0",NaN
650,1003629045,Chase Goehring debut EP,Music,Music,USD,2016-03-21 06:00:00,3000,2016-02-23 03:09:49,3660.38,undefined,0,"N,""0",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
323391,997971307,"EQUUS International Film Festival®, all-equine...",Film & Video,Film & Video,USD,2015-02-03 04:19:14,7500,2014-12-05 04:19:14,10,undefined,0,"N,""0",NaN
323456,998319149,Emily 2050 - Short Film,Film & Video,Film & Video,CAD,2014-05-23 00:30:09,3000,2014-04-08 00:30:09,3102,undefined,0,"N,""0",NaN
323561,9988744,Matthew Stephens Music,Music,Music,USD,2016-02-05 23:00:00,5000,2016-01-06 21:59:23,235,undefined,0,"N,""0",NaN
323683,999610349,Lady Vendredi: Afrofuturist concept 12 inch EP,Music,Music,GBP,2015-10-19 22:33:18,2000,2015-09-21 22:33:18,2125,undefined,0,"N,""0",NaN
323685,999621278,Jeune auteur a besoin de vous!,Publishing,Publishing,EUR,2015-11-20 21:28:13,1600,2015-10-21 21:28:13,0,undefined,0,"N,""0",NaN

In [47]:
df['usd_pledged'].unique()

<StringArray>
[            '0',           '220',             '1',          '1283',
         '52375',          '1205',           '453',          '8233',
       '6240.57',         '12700',
 ...
          '8935',         '42647',  '1673.7131361', '1937.69716526',
       '13861.5',  '4814.8774787',  '4281.1485734',       '1732.02',
 '5019.92088197',   '2698.974335']
Length: 94377, dtype: str

In [32]:
df

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09 11:36:00,1000,2015-08-11 12:12:28,0,failed,0,GB,0
1,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26 00:20:50,45000,2013-01-12 00:20:50,220,failed,3,US,220
2,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16 04:24:11,5000,2012-03-17 03:24:11,1,failed,1,US,1
3,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29 01:00:00,19500,2015-07-04 08:35:03,1283,canceled,14,US,1283
4,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01 13:38:27,50000,2016-02-26 13:38:27,52375,successful,224,US,52375
...,...,...,...,...,...,...,...,...,...,...,...,...,...
323745,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17 02:35:30,50000,2014-09-17 02:35:30,25,canceled,1,US,25
323746,999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19 03:35:14,1500,2011-06-22 03:35:14,155,failed,5,US,155
323747,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16 05:59:00,15000,2010-07-01 19:40:30,20,failed,1,US,20
323748,999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13 02:00:00,15000,2016-01-13 18:13:53,200,failed,6,US,200
323749,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16 09:07:47,2000,2011-07-19 09:07:47,524,failed,17,US,524

In [33]:
engine = create_engine('mysql+pymysql://root:Hahaha!1!@localhost:3306/kickstarter')

In [34]:
df.to_sql(
  name = 'ks_projects',
  con = engine,
  if_exists = 'append',
  index = False
)
print('Successfully added and loaded to kickstarter db')

DatabaseError: Execution failed on sql 'INSERT INTO ks_projects ("ID", name, category, main_category, currency, deadline, goal, launched, pledged, state, backers, country, usd_pledged) VALUES (:ID, :name, :category, :main_category, :currency, :deadline, :goal, :launched, :pledged, :state, :backers, :country, :usd_pledged)': (pymysql.err.OperationalError) (1292, "Incorrect datetime value: 'SEK' for column 'deadline' at row 1455")
[SQL: INSERT INTO ks_projects (`ID`, name, category, main_category, currency, deadline, goal, launched, pledged, state, backers, country, usd_pledged) VALUES (%(ID)s, %(name)s, %(category)s, %(main_category)s, %(currency)s, %(deadline)s, %(goal)s, %(launched)s, %(pledged)s, %(state)s, %(backers)s, %(country)s, %(usd_pledged)s)]
[parameters: [{'ID': 1000002330, 'name': 'The Songs of Adelaide & Abullah', 'category': 'Poetry', 'main_category': 'Publishing', 'currency': 'GBP', 'deadline': '2015-10-09 11:36:00', 'goal': '1000', 'launched': '2015-08-11 12:12:28', 'pledged': '0', 'state': 'failed', 'backers': '0', 'country': 'GB', 'usd_pledged': '0'}, {'ID': 1000004038, 'name': 'Where is Hank?', 'category': 'Narrative Film', 'main_category': 'Film & Video', 'currency': 'USD', 'deadline': '2013-02-26 00:20:50', 'goal': '45000', 'launched': '2013-01-12 00:20:50', 'pledged': '220', 'state': 'failed', 'backers': '3', 'country': 'US', 'usd_pledged': '220'}, {'ID': 1000007540, 'name': 'ToshiCapital Rekordz Needs Help to Complete Album', 'category': 'Music', 'main_category': 'Music', 'currency': 'USD', 'deadline': '2012-04-16 04:24:11', 'goal': '5000', 'launched': '2012-03-17 03:24:11', 'pledged': '1', 'state': 'failed', 'backers': '1', 'country': 'US', 'usd_pledged': '1'}, {'ID': 1000011046, 'name': 'Community Film Project: The Art of Neighborhood Filmmaking', 'category': 'Film & Video', 'main_category': 'Film & Video', 'currency': 'USD', 'deadline': '2015-08-29 01:00:00', 'goal': '19500', 'launched': '2015-07-04 08:35:03', 'pledged': '1283', 'state': 'canceled', 'backers': '14', 'country': 'US', 'usd_pledged': '1283'}, {'ID': 1000014025, 'name': 'Monarch Espresso Bar', 'category': 'Restaurants', 'main_category': 'Food', 'currency': 'USD', 'deadline': '2016-04-01 13:38:27', 'goal': '50000', 'launched': '2016-02-26 13:38:27', 'pledged': '52375', 'state': 'successful', 'backers': '224', 'country': 'US', 'usd_pledged': '52375'}, {'ID': 1000023410, 'name': 'Support Solar Roasted Coffee & Green Energy!  SolarCoffee.co', 'category': 'Food', 'main_category': 'Food', 'currency': 'USD', 'deadline': '2014-12-21 18:30:44', 'goal': '1000', 'launched': '2014-12-01 18:30:44', 'pledged': '1205', 'state': 'successful', 'backers': '16', 'country': 'US', 'usd_pledged': '1205'}, {'ID': 1000030581, 'name': 'Chaser Strips. Our Strips make Shots their B*tch!', 'category': 'Drinks', 'main_category': 'Food', 'currency': 'USD', 'deadline': '2016-03-17 19:05:12', 'goal': '25000', 'launched': '2016-02-01 20:05:12', 'pledged': '453', 'state': 'failed', 'backers': '40', 'country': 'US', 'usd_pledged': '453'}, {'ID': 1000034518, 'name': 'SPIN - Premium Retractable In-Ear Headphones with Mic', 'category': 'Product Design', 'main_category': 'Design', 'currency': 'USD', 'deadline': '2014-05-29 18:14:43', 'goal': '125000', 'launched': '2014-04-24 18:14:43', 'pledged': '8233', 'state': 'canceled', 'backers': '58', 'country': 'US', 'usd_pledged': '8233'}  ... displaying 10 of 323750 total bound parameter sets ...  {'ID': 999987933, 'name': 'BioDefense Education Kit', 'category': 'Technology', 'main_category': 'Technology', 'currency': 'USD', 'deadline': '2016-02-13 02:00:00', 'goal': '15000', 'launched': '2016-01-13 18:13:53', 'pledged': '200', 'state': 'failed', 'backers': '6', 'country': 'US', 'usd_pledged': '200'}, {'ID': 999988282, 'name': 'Nou Renmen Ayiti!  We Love Haiti!', 'category': 'Performance Art', 'main_category': 'Art', 'currency': 'USD', 'deadline': '2011-08-16 09:07:47', 'goal': '2000', 'launched': '2011-07-19 09:07:47', 'pledged': '524', 'state': 'failed', 'backers': '17', 'country': 'US', 'usd_pledged': '524'}]]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
sql_query = """
SELECT *
FROM ks_projects
LIMIT 20; """

In [ ]:
df_all = pd.read_sql(sql_query, con=engine)
df_all